### ISSUE TITLE
Readme.md Documentation

### ISSUE THREAD

**Issue by dekapd99** [theresatiffanytan/TripPal#11]
-Pembuatan Readme.md untuk keperluan dokumentasi dan instruksi instalasi
-Sesuaikan struktur folder dengan yang ada di Project

Co-authored-by: Tiffany <theresatiffanytanadji@gmail.com>
Co-authored-by: Gery <sebastiangerykris@gmail.com>

**Comment by sebastiangery** [comment]
sudah selesai tinggal ubah isinya aja
