### ISSUE TITLE
Code Documentation

### ISSUE THREAD

**Issue by dekapd99** [theresatiffanytan/TripPal#15]
Buat dokumentasi dari Code (jelaskan code secara singkat tapi cukup menjelaskan apa arti dari codenya dan pastikan tulis dokumentasi untuk code yang kemungkinan bisa lupa)

**Comment by theresatiffanytan** [comment]
Code documentation untuk home page sudah beres

**Comment by dekapd99** [comment]
Code documentation Detail Page done
