### ISSUE TITLE
pembuatan detail page

### ISSUE THREAD

**Issue by theresatiffanytan** [theresatiffanytan/TripPal#2]

**Comment by dekapd99** [comment]
Sudah selesai: 
-Halaman Detail Page Berhasil dibuat
-Slideshow sudah berhasil dibuat juga

Kekurangan: 
-Bug Layout Slideshow (nutupin layout selanjutnya karena yang dipake fullscreen)
-Pembuatan Grid Layout untuk Photos
-Pembuatan Button "How Do You Feel ?"
-Pembuatan Adding Name
